// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAT4WyG1RGMBSJaCdd7qlUADTgRHSR8N0',
    appId: '1:38919177110:web:a7ff738830844a318113b7',
    messagingSenderId: '38919177110',
    projectId: 'fluttar-f5da5',
    authDomain: 'fluttar-f5da5.firebaseapp.com',
    storageBucket: 'fluttar-f5da5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wPCHcEIphCaTFR0IhCTNTNJf2xNmyPY',
    appId: '1:38919177110:android:9d7439978b1737148113b7',
    messagingSenderId: '38919177110',
    projectId: 'fluttar-f5da5',
    storageBucket: 'fluttar-f5da5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2qD39JdwXaCMPLKLu8whdHpohxtmyfA',
    appId: '1:38919177110:ios:651ace95c12d05128113b7',
    messagingSenderId: '38919177110',
    projectId: 'fluttar-f5da5',
    storageBucket: 'fluttar-f5da5.appspot.com',
    iosClientId: '38919177110-iljf2fag6r1l4fb25d64e0urphhemlhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2qD39JdwXaCMPLKLu8whdHpohxtmyfA',
    appId: '1:38919177110:ios:12720e7aadde321d8113b7',
    messagingSenderId: '38919177110',
    projectId: 'fluttar-f5da5',
    storageBucket: 'fluttar-f5da5.appspot.com',
    iosClientId: '38919177110-cdjoh2k017ic77ua53ef2n65u9kpth83.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
